### ISSUE TITLE
Add CI and tests

### ISSUE THREAD

**Issue by normanrz** [scalableminds/wknml#12]
- [x] simple snapshot tests: Read fixture, write out and compare for equality.
- [x] add CircleCI builds that run the tests

**Comment by daniel-wer** [comment]
@leowe Not sure whether you already started with this, but I wanted to let you know that I fixed a bug in the group parsing/writing in #15. The code treated hierarchical groups as flat, so when parsing sth like this:
```xml
<groups>
  <group id="1" name="Axon 1">
      <group id="3" name="Blah" />
  </group>
  <group id="2" name="Axon 2" />
</groups>
```
when dumping it again, it resulted in this:
```xml
<groups>
  <group id="1" name="Axon 1" />
  <group id="3" name="Blah" />
  <group id="2" name="Axon 2" />
</groups>
```
Let me know once you have the snapshot tests and I'll make sure that a regression test for this is included :)

**Comment by georgwiese** [comment]
CC @MartinBuessemeyer 

What's the status here?

**Comment by leowe** [comment]
@georgwiese I finished most of it, wanted to wait until the other issue was finished. Could also make a PR now

**Comment by philippotto** [comment]
@leowe What's the status? Can you open the PR?
