### ISSUE TITLE
Implement better NML generation abstractions

### ISSUE THREAD

**Issue by georgwiese** [scalableminds/wknml#17]
Currently, our code to generate NMLs is pretty clumsy. It would be important that it is easy to use so that we can generate custom visualizations easily.

We need to put some thoughts into how to design this. Some nodes:
- Node IDs have to be global within one NML. Would be great if this would be handled transparently.
- Things like comments or branch points should just be node attributes.

**Comment by georgwiese** [comment]
We could just have a function that converts `networkx` graphs (which have things like the tree color as a tree attribute and things like position, comment, is_branchpoint as node attributes):

```python
def generate_nml(trees: Union[List[nx.Graph], Dict[str, nx.Graph]]) -> NML:
  """Convert networkX graphs to an NML object
  Arguments:
  - trees: Either a List of trees or a mapping of a group name to its list of trees.
  """
```

This is similar but more flexible to `segmentation.agglomeration.nml.generate_nml` in `segmentation-tools`. We could also add the function to this repo, but it might be useful for other projects too.

Also, we'd need the reverse function, because we might want directly put a tree from one NML to another.

**Comment by MartinBuessemeyer** [comment]
We decided in the sprint meeting to implement this into the `wknml`-repo.

**Comment by MartinBuessemeyer** [comment]
The generate function should globalize all ids. The Dict should make it possible to have multiple groups. Use `segmentation-tools/segmentation/agglomeration/nml.py` as codebase.
