### ISSUE TITLE
Support for multiple bounding boxes

### ISSUE THREAD

**Issue by normanrz** [scalableminds/wknml#44]
webKnossos supports multiple bounding boxes per annotation, but it seems like wknml doesn't handle them yet.

**Comment by hotzenklotz** [comment]
@erjel Do you only need support for the basic attributes (`topLeftX`, `topLeftY`, `topLeftZ`, `width`, `height`, `depth`) or also others (`color`, `name` etc) 

There is a PR that covers the basics: #45

**Comment by erjel** [comment]
Thank you (@hotzenklotz ) for the quick fix!

Currently, I only need support for the basic attributes.

In the near future:tm:, I can probably contribute a few test cases for this edge application from my private work-around :sweat_smile:.

**Comment by hotzenklotz** [comment]
@erjel The multi user bounding box support has been released as `wknml` version `1.1.0`
